### ISSUE TITLE
امکان گفتن اذان

### ISSUE THREAD

**Issue by mb-programmer** [ebraminio/DroidPersianCalendar#50]
سلام اگه بشه که امکان گفتن اذان رو هم اضافه کنی خیلی خوبه همین باد صبا رو حذف کنیم از رو گوشی

**Comment by mASOUDd** [comment]
من مخالفم.
به نظر من هر برنامه باید روی یک کار تمرکز کنه و اون کار رو خوب انجام بده.
این برنامه تقویم هست ربطی به اذان نداره
در مورد این موضوع:
http://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well
http://blog.codinghorror.com/why-does-software-spoil/

**Comment by mb-programmer** [comment]
سلام
@mASOUDd 
خوب میدونی چیه همین الان هم اگه ببینی میبینی که برنامه روی یک کار تمرکز نکرده و داره قبله نمایش میده، زمان تبدیل میکنه، اوقات شرعی نمایش میده 
پس فرقی نمیکنه که این کار رو هم انجام بده.
بعدش هم اینکه اگه بیشتر دقت کنی میبینی یادآوری از امکانات تقویم ها هست
حالا اگه امکان یادآوری اتوماتیک با توجه به زمان های اوقات شرعی که تو برنامه هست وجود داشتهخ باشه و همچنین امکان پخش فایل صوتی شخصی برای یاد آوری خیلی هم مفید هست برای برنامه تقویم هم کار بقیه رو راه میندازه
ممنون

**Comment by mASOUDd** [comment]
تبدیل تاریخ به تقویم مربوط می‌شه ولی به نظر من بهتره که اوقات شرعی و قبله نما و اذان گو رو تبدیل کنیم به یه برنامه جدا.

**Comment by mozaffari** [comment]
به نظر من هم باید اذان رو اضافه کنین
بقول دوستمون mb-programmer 
از شر باد و صبا دیگه برنامه های که عامل سقوط باطری هست جلوگیری بشه

**Comment by hamidsafdari** [comment]
@ebraminio, I'm still not sure about the Athan setting. The location of the Alarms folder is different on different Android versions. For example I had to copy the sound file to /sdcard/media/audio/Alarms so it could be seen in the Alarms dialog.
This location doesn't work for other Android versions. The Android API let's you determine the location of the Alarms  folder as /sdcard/Alarms but if  you put something in there it wouldn't be seen in the  Alarms dialog.

I just skipped copying the file to different folders and have written in the "summary" of the "Athan Sound" setting that if the user wants the default Athan sound, he can choose None/Silent.

That's not really good because you don't get a preview of the Athan file. I'll be glad if  somebody could point us to some instructions regarding the location of different Sound folders on different Android versions.

**Comment by ebraminio** [comment]
بله امکان زبان اضافه شده من هم از آن استفاذه کرده‌ام فقط نیاز است برنامه پایدار شود :)
